### PR TITLE
Fix/Remove debug

### PR DESCRIPTION
**Pull request by andrii-bodnar**
This PR just removes the console logs. It's not ok to do such things in a production version of the component.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @camwiegert, @mlynch, @perrygovier, @jthoms1!

Thanks a lot for this component!

Please review this request and release a new version to npm. It's important for us.

**Comment by andrii-bodnar** [comment]
@camwiegert, @mlynch, @perrygovier, @jthoms1 just a friendly reminder

**Comment by andrii-bodnar** [comment]
Hi @camwiegert, @mlynch, @perrygovier, @jthoms1, @jcesarmobile, @kensodemann, @liamdebeasi, @connersimmons, @carlpoole!

Can someone review this pull request? 😄 

I am using the stencil-helmet and these console logs are annoying and forcing me to disable info logs at all

**Review by rwaskiewicz — APPROVED** [review]

**Comment by rwaskiewicz** [comment]
@andrii-bodnar 👋 

I've merged this PR, thanks! I will look to cut a release later today.

I would encourage you to avoid directly pinging team members (some of the folks you've reached out to are no longer affiliated with Ionic). While some individuals may appreciate the reminder, others may also find it to be interrupting or distracting. As a best practice, I tend not to tag individuals unless they are already involved in the conversation and I am replying to them.

**Comment by andrii-bodnar** [comment]
Hi @rwaskiewicz, thank you!

> I would encourage you to avoid directly pinging team members

Sorry for that, it seemed to me that no one was following the repository and I had to do it to get some attention. The fix is minor and it took more than 20 days to merge :(

**Pull request merged**
